class UserAlreadyExistsException(Exception):
    pass

class LoginException(Exception):
    pass